const divPrincipal = document.getElementsByTagName("div")[0];
const criarDiv1 = document.createElement("div");
criarDiv1.innerHTML += "<p>Texto qualquer </p>";
divPrincipal.appendChild(criarDiv1);
const criarDiv2 = document.createElement("div");
criarDiv2.innerHTML += "<p>Texto qualquer </p>";
divPrincipal.appendChild(criarDiv2);
const criarDiv3 = document.createElement("div");
criarDiv3.innerHTML += "<p>Texto qualquer </p>";
divPrincipal.appendChild(criarDiv3);
const criarDiv4 = document.createElement("div");
criarDiv4.innerHTML += "<p>Texto qualquer </p>";
divPrincipal.appendChild(criarDiv4);
